apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bifract

resources:
  - namespace.yaml
  - clickhouse/clickhouse-installation.yaml
  - postgres/statefulset.yaml
  - bifract/deployment.yaml
  - bifract/configmap.yaml
  - bifract/secrets.yaml
  - caddy/deployment.yaml
  - caddy/configmap.yaml
  - caddy/log-shipper.yaml
  - litellm/deployment.yaml
  - litellm/configmap.yaml
  - network-policies.yaml
