package setup

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

func ReadEnvFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	env := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			env[parts[0]] = parts[1]
		}
	}
	return env, scanner.Err()
}

func WriteEnvFile(path string, env map[string]string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	fmt.Fprintln(f, "# Generated by bifract "+Version)
	fmt.Fprintln(f, "# Do not edit manually unless you know what you are doing.")
	fmt.Fprintln(f)
	for _, k := range keys {
		fmt.Fprintf(f, "%s=%s\n", k, env[k])
	}
	return nil
}

// MergeEnv merges new keys into existing, preserving existing values.
func MergeEnv(existing, defaults map[string]string) map[string]string {
	merged := make(map[string]string)
	for k, v := range defaults {
		merged[k] = v
	}
	for k, v := range existing {
		merged[k] = v
	}
	return merged
}
