package setup

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	dbsql "bifract/db"
)

func RenderDockerCompose(cfg *SetupConfig) (string, error) {
	return renderTemplate("templates/docker-compose.yml.tmpl", cfg)
}

func RenderCaddyfile(cfg *SetupConfig) (string, error) {
	return renderTemplate("templates/Caddyfile.tmpl", cfg)
}

// defaultAdminHash is the hardcoded default admin password hash in db/init-postgres.sql.
// RenderInitPostgres replaces it with the setup-generated hash so there is a single
// source of truth for the Postgres schema (db/init-postgres.sql).
const defaultAdminHash = "$2a$10$r0TpEb0RiqoaP2HuhvDzaONZe0jaTpjlqzGY3.xY8ZqrvjZNNyOBC"

func RenderInitPostgres(cfg *SetupConfig) (string, error) {
	sql := strings.Replace(dbsql.PostgresSQL, defaultAdminHash, cfg.AdminPasswordHash, 1)
	// bifract generates a random admin password, so disable forced password change.
	// The default init SQL sets force_password_change=TRUE for the hardcoded admin:bifract credentials.
	sql = strings.Replace(sql, "TRUE,\n    TRUE\n)\nON CONFLICT", "TRUE,\n    FALSE\n)\nON CONFLICT", 1)
	return sql, nil
}

func RenderInitClickHouse(_ *SetupConfig) (string, error) {
	return dbsql.ClickHouseSQL, nil
}

func RenderEnvFile(cfg *SetupConfig) string {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Generated by bifract "+Version)
	fmt.Fprintln(&b, "# Do not edit manually unless you know what you are doing.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "BIFRACT_VERSION=%s\n", cfg.ImageTag)
	fmt.Fprintf(&b, "BIFRACT_DOMAIN=%s\n", cfg.Domain)
	fmt.Fprintf(&b, "POSTGRES_PASSWORD=%s\n", cfg.PostgresPassword)
	fmt.Fprintf(&b, "CLICKHOUSE_PASSWORD=%s\n", cfg.ClickHousePassword)
	fmt.Fprintf(&b, "LITELLM_MASTER_KEY=%s\n", cfg.LiteLLMMasterKey)
	fmt.Fprintf(&b, "LITELLM_MODEL=%s\n", cfg.LiteLLMModel)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# AI chat (optional - see docs/features/ai-chat.md)")
	fmt.Fprintln(&b, "# OPENAI_API_KEY=")
	fmt.Fprintln(&b, "# ANTHROPIC_API_KEY=")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "BIFRACT_SECURE_COOKIES=%t\n", cfg.SecureCookies)
	fmt.Fprintf(&b, "BIFRACT_CORS_ORIGINS=%s\n", cfg.CORSOrigins)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# SSL configuration (used during upgrades to preserve settings)")
	fmt.Fprintf(&b, "BIFRACT_SSL_MODE=%s\n", cfg.SSLMode)
	fmt.Fprintf(&b, "BIFRACT_SSL_EMAIL=%s\n", cfg.SSLEmail)
	fmt.Fprintf(&b, "BIFRACT_CERT_PATH=%s\n", cfg.CertPath)
	fmt.Fprintf(&b, "BIFRACT_KEY_PATH=%s\n", cfg.KeyPath)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# IP access control (all, restrict-app, restrict-all, mtls-app)")
	fmt.Fprintf(&b, "BIFRACT_IP_ACCESS=%s\n", cfg.IPAccess)
	fmt.Fprintf(&b, "BIFRACT_ALLOWED_IPS=%s\n", cfg.AllowedIPsString())
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# Password pepper (HMAC secret for password hashing, do NOT change after install)")
	fmt.Fprintf(&b, "BIFRACT_PASSWORD_PEPPER=%s\n", cfg.PasswordPepper)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# Feed encryption key (AES-256, hex-encoded 32 bytes, do NOT change after install)")
	fmt.Fprintf(&b, "BIFRACT_FEED_ENCRYPTION_KEY=%s\n", cfg.FeedEncryptionKey)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# Backup encryption key (AES-256, hex-encoded 32 bytes)")
	fmt.Fprintf(&b, "BIFRACT_BACKUP_ENCRYPTION_KEY=%s\n", cfg.BackupEncryptionKey)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# Backup storage (optional S3-compatible)")
	fmt.Fprintf(&b, "BIFRACT_S3_ENDPOINT=%s\n", cfg.S3Endpoint)
	fmt.Fprintf(&b, "BIFRACT_S3_BUCKET=%s\n", cfg.S3Bucket)
	fmt.Fprintf(&b, "BIFRACT_S3_ACCESS_KEY=%s\n", cfg.S3AccessKey)
	fmt.Fprintf(&b, "BIFRACT_S3_SECRET_KEY=%s\n", cfg.S3SecretKey)
	fmt.Fprintf(&b, "BIFRACT_S3_REGION=%s\n", cfg.S3Region)
	return b.String()
}

func renderTemplate(name string, data interface{}) (string, error) {
	content, err := TemplateFS.ReadFile(name)
	if err != nil {
		return "", fmt.Errorf("read template %s: %w", name, err)
	}

	tmpl, err := template.New(filepath.Base(name)).Parse(string(content))
	if err != nil {
		return "", fmt.Errorf("parse template %s: %w", name, err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template %s: %w", name, err)
	}
	return buf.String(), nil
}

func CopyEmbeddedFile(name, destPath string) error {
	content, err := TemplateFS.ReadFile(name)
	if err != nil {
		return fmt.Errorf("read embedded %s: %w", name, err)
	}
	if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(destPath, content, 0755)
}

// WriteAllFiles generates and writes all configuration files to the install directory.
func WriteAllFiles(cfg *SetupConfig) error {
	dir := cfg.InstallDir

	compose, err := RenderDockerCompose(cfg)
	if err != nil {
		return fmt.Errorf("render docker-compose: %w", err)
	}
	if err := writeFile(filepath.Join(dir, "docker-compose.yml"), compose); err != nil {
		return err
	}

	envContent := RenderEnvFile(cfg)
	if err := writeSecretFile(filepath.Join(dir, ".env"), envContent); err != nil {
		return err
	}

	caddyfile, err := RenderCaddyfile(cfg)
	if err != nil {
		return fmt.Errorf("render caddyfile: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "caddy"), 0755); err != nil {
		return err
	}
	if err := writeFile(filepath.Join(dir, "caddy", "Caddyfile"), caddyfile); err != nil {
		return err
	}

	// Generate or copy TLS certificates for self-signed and custom modes.
	certsDir := filepath.Join(dir, "caddy", "certs")
	switch cfg.SSLMode {
	case SSLSelfSigned:
		if err := GenerateSelfSignedCert(cfg.Domain, certsDir); err != nil {
			return fmt.Errorf("generate self-signed cert: %w", err)
		}
	case SSLCustom:
		if cfg.CertPath != "" && cfg.KeyPath != "" {
			if err := copyCertsToDir(cfg.CertPath, cfg.KeyPath, certsDir); err != nil {
				return fmt.Errorf("copy custom certs: %w", err)
			}
		}
	}

	// Generate client CA for mTLS mode.
	if cfg.IPAccess == IPAccessMTLSApp {
		caDir := filepath.Join(dir, "caddy", "client-ca")
		if err := GenerateClientCA(caDir); err != nil {
			return fmt.Errorf("generate client CA: %w", err)
		}
	}

	if err := CopyEmbeddedFile("templates/entrypoint.sh", filepath.Join(dir, "caddy", "entrypoint.sh")); err != nil {
		return err
	}
	if err := CopyEmbeddedFile("templates/ship-logs.sh", filepath.Join(dir, "caddy", "ship-logs.sh")); err != nil {
		return err
	}

	initPG, err := RenderInitPostgres(cfg)
	if err != nil {
		return fmt.Errorf("render init-postgres: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "db"), 0755); err != nil {
		return err
	}
	if err := writeFile(filepath.Join(dir, "db", "init-postgres.sql"), initPG); err != nil {
		return err
	}

	initCH, err := RenderInitClickHouse(cfg)
	if err != nil {
		return fmt.Errorf("render init-clickhouse: %w", err)
	}
	if err := writeFile(filepath.Join(dir, "db", "init-clickhouse.sql"), initCH); err != nil {
		return err
	}

	if err := CopyEmbeddedFile("templates/litellm-config.yaml", filepath.Join(dir, "litellm-config.yaml")); err != nil {
		return err
	}

	return nil
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0644)
}

func writeSecretFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0600)
}
