-- Add a minmax index on logs.ingest_timestamp.
--
-- Scheduled model maintenance reads an ingest-time window each cycle. The partition key is
-- (fractal_id, toDate(ingest_timestamp)), so a window prunes to the day but not within it: every
-- run reads the whole current day's parts. Measured on a 2M-row day: a two-hour window reads 28k
-- rows with the index and 200k without.
--
-- Metadata-only. Existing parts carry no index until they are merged or MATERIALIZE INDEX is run;
-- new parts get it immediately, which is what the scheduled reader needs since it only ever looks
-- at recent ingest. No data pass is issued here: on a billion-row table that is hours of IO for an
-- index whose value is entirely in the newest parts.
ALTER TABLE logs ADD INDEX IF NOT EXISTS idx_ingest_ts ingest_timestamp TYPE minmax GRANULARITY 1;
