-- Migration 002: neutralized (was: JSON type hints + skip indexes).
--
-- The original migration ran ALTER TABLE logs MODIFY COLUMN fields JSON(...) from a
-- fixed field list. MODIFY COLUMN replaces the entire JSON definition, so it stripped
-- any custom type hints added through the schema UI and invalidated their dependent
-- skip indexes (ClickHouse code 44: bloom_filter index on a Dynamic column), aborting
-- the migration and, with it, app startup.
--
-- Type hint and skip index management now lives entirely in ReconcileSchemaFields,
-- which runs at every app startup and merges project defaults with custom fields
-- non-destructively. The default hints are also present in db/init-clickhouse.sql for
-- fresh installs. This migration is therefore redundant and is kept only as a no-op so
-- that migration numbering stays contiguous (001-005) across docker and k8s.
--
-- SELECT 1 is a harmless no-op: the app's runner only executes CREATE/ALTER statements
-- (so it skips this), and bifract-setup's runner executes it without side effects.
SELECT 1;
