package main

// routeTable is every route the server mounts, in the form:
//
//	METHOD /path <middleware count> auth|public [body] [resp] <access>
//
// "auth" means the route sits behind auth.AuthHandler.AuthMiddleware; "body"
// and "resp" mean the route declares a typed request and response; the last
// field is the access level the route enforces.
//
// Regenerate after an intended change, then review every line of the diff:
//
//	go test ./cmd/bifract-server -run TestRouteTable -update
var routeTable = []string{
	"GET /* 7 public public",
	"POST /_bulk 8 public body resp ingest_token",
	"PUT /_bulk 8 public body resp ingest_token",
	"GET /api/v1/admin/activity 9 auth resp tenant_admin",
	"GET /api/v1/admin/activity/detail 9 auth resp tenant_admin",
	"GET /api/v1/admin/activity/summary 9 auth resp tenant_admin",
	"GET /api/v1/admin/alert-stats 9 auth resp tenant_admin",
	"GET /api/v1/admin/alert-stats/rows 9 auth resp tenant_admin",
	"GET /api/v1/admin/background 9 auth resp tenant_admin",
	"GET /api/v1/admin/hot-table 9 auth resp tenant_admin",
	"GET /api/v1/admin/ingest-daily 9 auth resp tenant_admin",
	"POST /api/v1/admin/kill-query 9 auth resp tenant_admin",
	"GET /api/v1/admin/metrics 9 auth resp tenant_admin",
	"GET /api/v1/admin/processes 9 auth resp tenant_admin",
	"GET /api/v1/admin/schema-fields 9 auth resp tenant_admin",
	"POST /api/v1/admin/schema-fields 9 auth body resp tenant_admin",
	"GET /api/v1/admin/schema-fields/export 9 auth tenant_admin",
	"DELETE /api/v1/admin/schema-fields/ignore/{name} 9 auth resp tenant_admin",
	"POST /api/v1/admin/schema-fields/ignore/{name} 9 auth resp tenant_admin",
	"POST /api/v1/admin/schema-fields/import 9 auth body resp tenant_admin",
	"GET /api/v1/admin/schema-fields/insights 9 auth resp tenant_admin",
	"POST /api/v1/admin/schema-fields/refresh 9 auth resp tenant_admin",
	"POST /api/v1/admin/schema-fields/reset 9 auth body resp tenant_admin",
	"DELETE /api/v1/admin/schema-fields/{name} 9 auth resp tenant_admin",
	"GET /api/v1/alert-changes 9 auth resp viewer",
	"POST /api/v1/alert-changes 9 auth body resp analyst",
	"DELETE /api/v1/alert-changes/{id} 9 auth resp fractal_admin",
	"GET /api/v1/alert-changes/{id} 9 auth resp viewer",
	"PUT /api/v1/alert-changes/{id} 9 auth body resp analyst",
	"POST /api/v1/alert-changes/{id}/discard 9 auth resp analyst",
	"POST /api/v1/alert-changes/{id}/merge 9 auth resp analyst",
	"POST /api/v1/alert-changes/{id}/review 9 auth body resp analyst",
	"GET /api/v1/alert-gate 9 auth resp viewer",
	"PUT /api/v1/alert-gate 9 auth body resp fractal_admin",
	"GET /api/v1/alert-policies 9 auth resp viewer",
	"PUT /api/v1/alert-policies 9 auth body resp fractal_admin",
	"GET /api/v1/alert-policies/catalog 9 auth resp viewer",
	"GET /api/v1/alert-policies/compliance 9 auth resp viewer",
	"POST /api/v1/alert-policies/evaluate 9 auth body resp viewer",
	"GET /api/v1/alert-policies/export 9 auth resp viewer",
	"POST /api/v1/alert-policies/import 9 auth body resp fractal_admin",
	"GET /api/v1/alerts 9 auth resp viewer",
	"POST /api/v1/alerts 9 auth body resp analyst",
	"POST /api/v1/alerts/batch-toggle 9 auth body resp analyst",
	"GET /api/v1/alerts/feed 9 auth resp viewer",
	"POST /api/v1/alerts/feed/batch-toggle 9 auth body resp analyst",
	"POST /api/v1/alerts/import 9 auth body resp analyst",
	"POST /api/v1/alerts/tests/run 9 auth body resp analyst",
	"DELETE /api/v1/alerts/tests/session/{sessionId} 9 auth resp analyst",
	"DELETE /api/v1/alerts/{id} 9 auth analyst",
	"GET /api/v1/alerts/{id} 9 auth resp viewer",
	"PUT /api/v1/alerts/{id} 9 auth body resp analyst",
	"GET /api/v1/alerts/{id}/activity 9 auth resp viewer",
	"POST /api/v1/alerts/{id}/duplicate 9 auth resp viewer",
	"GET /api/v1/alerts/{id}/executions 9 auth resp viewer",
	"GET /api/v1/alerts/{id}/revisions 9 auth resp viewer",
	"GET /api/v1/alerts/{id}/revisions/{revision} 9 auth resp viewer",
	"POST /api/v1/alerts/{id}/revisions/{revision}/restore 9 auth body resp analyst",
	"GET /api/v1/alerts/{id}/tests 9 auth resp viewer",
	"POST /api/v1/alerts/{id}/toggle-feed 9 auth body viewer",
	"GET /api/v1/api-keys 9 auth resp tenant_admin",
	"POST /api/v1/api-keys 9 auth body resp tenant_admin",
	"DELETE /api/v1/api-keys/{keyId} 9 auth tenant_admin",
	"GET /api/v1/api-keys/{keyId} 9 auth resp tenant_admin",
	"PUT /api/v1/api-keys/{keyId} 9 auth body resp tenant_admin",
	"POST /api/v1/api-keys/{keyId}/toggle 9 auth resp tenant_admin",
	"GET /api/v1/attack/coverage 9 auth resp viewer",
	"GET /api/v1/attack/gaps 9 auth resp viewer",
	"GET /api/v1/attack/layer 9 auth viewer",
	"GET /api/v1/attack/matrix 9 auth resp viewer",
	"GET /api/v1/attack/techniques/{id}/gap 9 auth resp viewer",
	"GET /api/v1/attack/techniques/{id}/rules 9 auth resp viewer",
	"POST /api/v1/auth/admin-reset-mfa 9 auth body resp tenant_admin",
	"POST /api/v1/auth/admin-reset-password 9 auth body resp tenant_admin",
	"POST /api/v1/auth/change-password 9 auth body resp viewer",
	"POST /api/v1/auth/invite/accept 7 public body resp public",
	"POST /api/v1/auth/invite/reset 9 auth body resp tenant_admin",
	"GET /api/v1/auth/invite/validate 7 public resp public",
	"POST /api/v1/auth/login 7 public body public",
	"POST /api/v1/auth/logout 9 auth resp authenticated",
	"POST /api/v1/auth/mfa/confirm 9 auth body resp authenticated",
	"POST /api/v1/auth/mfa/disable 9 auth body resp authenticated",
	"POST /api/v1/auth/mfa/enroll 9 auth resp authenticated",
	"POST /api/v1/auth/mfa/recovery-codes 9 auth body resp authenticated",
	"GET /api/v1/auth/mfa/status 9 auth resp authenticated",
	"POST /api/v1/auth/mfa/verify 9 auth body resp authenticated",
	"GET /api/v1/auth/oidc/callback 7 public public",
	"GET /api/v1/auth/oidc/config 7 public public",
	"GET /api/v1/auth/oidc/login 7 public public",
	"PATCH /api/v1/auth/preferences 9 auth body resp viewer",
	"POST /api/v1/auth/register 9 auth body resp tenant_admin",
	"GET /api/v1/auth/user 9 auth resp authenticated",
	"DELETE /api/v1/chat/conversations 10 auth resp authenticated",
	"GET /api/v1/chat/conversations 10 auth resp viewer",
	"POST /api/v1/chat/conversations 10 auth body resp viewer",
	"DELETE /api/v1/chat/conversations/{id} 10 auth resp viewer",
	"PATCH /api/v1/chat/conversations/{id} 10 auth body resp viewer",
	"GET /api/v1/chat/conversations/{id}/libraries 10 auth resp viewer",
	"PATCH /api/v1/chat/conversations/{id}/libraries 10 auth body resp viewer",
	"DELETE /api/v1/chat/conversations/{id}/messages 10 auth resp viewer",
	"GET /api/v1/chat/conversations/{id}/messages 10 auth resp viewer",
	"POST /api/v1/chat/conversations/{id}/stream 10 auth body viewer",
	"GET /api/v1/chat/conversations/{id}/tool-calls 10 auth resp viewer",
	"POST /api/v1/chat/conversations/{id}/tool-calls/{callId}/stream 10 auth body viewer",
	"GET /api/v1/chat/instructions 9 auth resp viewer",
	"POST /api/v1/chat/instructions 9 auth body resp viewer",
	"DELETE /api/v1/chat/instructions/{instructionId} 9 auth resp viewer",
	"PUT /api/v1/chat/instructions/{instructionId} 9 auth body resp viewer",
	"POST /api/v1/comments 9 auth body resp analyst",
	"POST /api/v1/comments/bulk-add-tag 9 auth body analyst",
	"POST /api/v1/comments/bulk-delete 9 auth body analyst",
	"POST /api/v1/comments/bulk-remove-tag 9 auth body analyst",
	"GET /api/v1/comments/flat 9 auth resp viewer",
	"POST /api/v1/comments/graph/log-fields 9 auth body resp viewer",
	"GET /api/v1/comments/tags 9 auth resp viewer",
	"DELETE /api/v1/comments/{id} 9 auth resp viewer",
	"GET /api/v1/comments/{id} 9 auth resp viewer",
	"PUT /api/v1/comments/{id} 9 auth body resp viewer",
	"PUT /api/v1/comments/{id}/tags 9 auth body resp analyst",
	"GET /api/v1/context-links 9 auth resp tenant_admin",
	"POST /api/v1/context-links 9 auth body resp tenant_admin",
	"GET /api/v1/context-links/enabled 9 auth resp viewer",
	"DELETE /api/v1/context-links/{id} 9 auth resp tenant_admin",
	"GET /api/v1/context-links/{id} 9 auth resp tenant_admin",
	"PUT /api/v1/context-links/{id} 9 auth body resp tenant_admin",
	"GET /api/v1/dashboards 9 auth resp viewer",
	"POST /api/v1/dashboards 9 auth body resp analyst",
	"POST /api/v1/dashboards/import 9 auth body resp analyst",
	"DELETE /api/v1/dashboards/{id} 9 auth resp viewer",
	"GET /api/v1/dashboards/{id} 9 auth resp viewer",
	"PUT /api/v1/dashboards/{id} 9 auth body resp viewer",
	"GET /api/v1/dashboards/{id}/events 9 auth viewer",
	"POST /api/v1/dashboards/{id}/execute 9 auth resp viewer",
	"GET /api/v1/dashboards/{id}/export 9 auth viewer",
	"GET /api/v1/dashboards/{id}/presence 9 auth resp viewer",
	"POST /api/v1/dashboards/{id}/presence 9 auth resp viewer",
	"PUT /api/v1/dashboards/{id}/refresh-interval 9 auth body resp viewer",
	"GET /api/v1/dashboards/{id}/shared-links 9 auth resp viewer",
	"POST /api/v1/dashboards/{id}/shared-links 9 auth body tenant_admin",
	"DELETE /api/v1/dashboards/{id}/shared-links/{link_id} 9 auth resp viewer",
	"PUT /api/v1/dashboards/{id}/variables 9 auth body resp viewer",
	"POST /api/v1/dashboards/{id}/widgets 9 auth body resp viewer",
	"DELETE /api/v1/dashboards/{id}/widgets/{widget_id} 9 auth resp viewer",
	"PUT /api/v1/dashboards/{id}/widgets/{widget_id} 9 auth body resp viewer",
	"POST /api/v1/dashboards/{id}/widgets/{widget_id}/execute 9 auth body viewer",
	"PUT /api/v1/dashboards/{id}/widgets/{widget_id}/layout 9 auth body resp viewer",
	"GET /api/v1/dictionaries 9 auth resp viewer",
	"POST /api/v1/dictionaries 9 auth body resp analyst",
	"DELETE /api/v1/dictionaries/{id} 9 auth resp analyst",
	"GET /api/v1/dictionaries/{id} 9 auth resp viewer",
	"PUT /api/v1/dictionaries/{id} 9 auth body resp analyst",
	"POST /api/v1/dictionaries/{id}/columns 9 auth body resp analyst",
	"DELETE /api/v1/dictionaries/{id}/columns/{name} 9 auth resp analyst",
	"DELETE /api/v1/dictionaries/{id}/columns/{name}/key 9 auth resp analyst",
	"POST /api/v1/dictionaries/{id}/columns/{name}/key 9 auth resp analyst",
	"GET /api/v1/dictionaries/{id}/data 9 auth resp viewer",
	"POST /api/v1/dictionaries/{id}/data 9 auth body resp analyst",
	"DELETE /api/v1/dictionaries/{id}/data/{key} 9 auth resp analyst",
	"GET /api/v1/dictionaries/{id}/export 9 auth viewer",
	"POST /api/v1/dictionaries/{id}/import 9 auth body resp analyst",
	"POST /api/v1/dictionaries/{id}/reload 9 auth resp analyst",
	"GET /api/v1/dictionary-actions 9 auth resp viewer",
	"POST /api/v1/dictionary-actions 9 auth body resp analyst",
	"DELETE /api/v1/dictionary-actions/{id} 9 auth resp analyst",
	"GET /api/v1/dictionary-actions/{id} 9 auth resp viewer",
	"PUT /api/v1/dictionary-actions/{id} 9 auth body resp analyst",
	"GET /api/v1/email-actions 9 auth resp tenant_admin",
	"POST /api/v1/email-actions 9 auth body resp tenant_admin",
	"DELETE /api/v1/email-actions/{id} 9 auth tenant_admin",
	"GET /api/v1/email-actions/{id} 9 auth resp tenant_admin",
	"PUT /api/v1/email-actions/{id} 9 auth body resp tenant_admin",
	"POST /api/v1/email-actions/{id}/test 9 auth resp tenant_admin",
	"GET /api/v1/feeds 9 auth resp viewer",
	"POST /api/v1/feeds 9 auth body resp tenant_admin",
	"DELETE /api/v1/feeds/{id} 9 auth tenant_admin",
	"GET /api/v1/feeds/{id} 9 auth resp viewer",
	"PUT /api/v1/feeds/{id} 9 auth body resp tenant_admin",
	"GET /api/v1/feeds/{id}/alerts 9 auth resp viewer",
	"POST /api/v1/feeds/{id}/alerts/disable-all 9 auth tenant_admin",
	"POST /api/v1/feeds/{id}/alerts/enable-all 9 auth tenant_admin",
	"POST /api/v1/feeds/{id}/sync 9 auth tenant_admin",
	"GET /api/v1/fractal-actions 9 auth resp tenant_admin",
	"POST /api/v1/fractal-actions 9 auth body resp tenant_admin",
	"DELETE /api/v1/fractal-actions/{id} 9 auth tenant_admin",
	"GET /api/v1/fractal-actions/{id} 9 auth resp tenant_admin",
	"PUT /api/v1/fractal-actions/{id} 9 auth body resp tenant_admin",
	"GET /api/v1/fractals 9 auth resp viewer",
	"POST /api/v1/fractals 9 auth body resp tenant_admin",
	"POST /api/v1/fractals/stats/refresh 9 auth tenant_admin",
	"DELETE /api/v1/fractals/{id} 9 auth tenant_admin",
	"GET /api/v1/fractals/{id} 9 auth resp tenant_admin",
	"PUT /api/v1/fractals/{id} 9 auth body resp tenant_admin",
	"GET /api/v1/fractals/{id}/api-keys 9 auth resp tenant_admin",
	"POST /api/v1/fractals/{id}/api-keys 9 auth body resp tenant_admin",
	"DELETE /api/v1/fractals/{id}/api-keys/{keyId} 9 auth tenant_admin",
	"GET /api/v1/fractals/{id}/api-keys/{keyId} 9 auth resp tenant_admin",
	"PUT /api/v1/fractals/{id}/api-keys/{keyId} 9 auth body resp tenant_admin",
	"POST /api/v1/fractals/{id}/api-keys/{keyId}/toggle 9 auth resp tenant_admin",
	"PUT /api/v1/fractals/{id}/archive-retention 9 auth body tenant_admin",
	"PUT /api/v1/fractals/{id}/disk-quota 9 auth body tenant_admin",
	"GET /api/v1/fractals/{id}/ingest-tokens 9 auth resp tenant_admin",
	"POST /api/v1/fractals/{id}/ingest-tokens 9 auth body resp tenant_admin",
	"DELETE /api/v1/fractals/{id}/ingest-tokens/{tokenId} 9 auth tenant_admin",
	"GET /api/v1/fractals/{id}/ingest-tokens/{tokenId} 9 auth resp tenant_admin",
	"PUT /api/v1/fractals/{id}/ingest-tokens/{tokenId} 9 auth body resp tenant_admin",
	"POST /api/v1/fractals/{id}/ingest-tokens/{tokenId}/toggle 9 auth resp tenant_admin",
	"GET /api/v1/fractals/{id}/permissions 9 auth resp tenant_admin",
	"POST /api/v1/fractals/{id}/permissions 9 auth body resp tenant_admin",
	"DELETE /api/v1/fractals/{id}/permissions/{permId} 9 auth tenant_admin",
	"PUT /api/v1/fractals/{id}/permissions/{permId} 9 auth body tenant_admin",
	"PUT /api/v1/fractals/{id}/retention 9 auth body tenant_admin",
	"POST /api/v1/fractals/{id}/select 9 auth resp viewer",
	"GET /api/v1/fractals/{id}/stats 9 auth resp tenant_admin",
	"GET /api/v1/groups 9 auth tenant_admin",
	"POST /api/v1/groups 9 auth body tenant_admin",
	"DELETE /api/v1/groups/{id} 9 auth tenant_admin",
	"GET /api/v1/groups/{id} 9 auth tenant_admin",
	"PUT /api/v1/groups/{id} 9 auth body tenant_admin",
	"GET /api/v1/groups/{id}/members 9 auth tenant_admin",
	"POST /api/v1/groups/{id}/members 9 auth body tenant_admin",
	"DELETE /api/v1/groups/{id}/members/{username} 9 auth tenant_admin",
	"GET /api/v1/health 7 public public",
	"GET /api/v1/health/clickhouse 9 auth viewer",
	"POST /api/v1/ingest 8 public body resp ingest_token",
	"GET /api/v1/instruction-libraries 9 auth resp viewer",
	"POST /api/v1/instruction-libraries 9 auth body resp analyst",
	"GET /api/v1/instruction-libraries/ensure-default 9 auth resp viewer",
	"DELETE /api/v1/instruction-libraries/{id} 9 auth fractal_admin",
	"GET /api/v1/instruction-libraries/{id} 9 auth resp viewer",
	"PUT /api/v1/instruction-libraries/{id} 9 auth body resp analyst",
	"GET /api/v1/instruction-libraries/{id}/folders 9 auth resp viewer",
	"POST /api/v1/instruction-libraries/{id}/folders 9 auth body resp analyst",
	"DELETE /api/v1/instruction-libraries/{id}/folders/{folderId} 9 auth analyst",
	"PUT /api/v1/instruction-libraries/{id}/folders/{folderId} 9 auth body resp analyst",
	"GET /api/v1/instruction-libraries/{id}/pages 9 auth resp viewer",
	"POST /api/v1/instruction-libraries/{id}/pages 9 auth body resp analyst",
	"DELETE /api/v1/instruction-libraries/{id}/pages/{pageId} 9 auth fractal_admin",
	"GET /api/v1/instruction-libraries/{id}/pages/{pageId} 9 auth resp viewer",
	"PUT /api/v1/instruction-libraries/{id}/pages/{pageId} 9 auth body resp analyst",
	"GET /api/v1/instruction-libraries/{id}/pages/{pageId}/backlinks 9 auth resp viewer",
	"PATCH /api/v1/instruction-libraries/{id}/pages/{pageId}/move 9 auth body analyst",
	"POST /api/v1/instruction-libraries/{id}/sync 9 auth resp fractal_admin",
	"POST /api/v1/internal/ingest/{fractal} 9 public body resp internal",
	"DELETE /api/v1/logs 9 auth resp tenant_admin",
	"POST /api/v1/logs/by-timestamp 9 auth body resp viewer",
	"GET /api/v1/logs/commented 9 auth resp viewer",
	"GET /api/v1/logs/fields 9 auth resp viewer",
	"GET /api/v1/logs/histogram 9 auth viewer",
	"GET /api/v1/logs/recent 9 auth viewer",
	"DELETE /api/v1/logs/{log_id}/comments 9 auth resp fractal_admin",
	"GET /api/v1/logs/{log_id}/comments 9 auth resp viewer",
	"GET /api/v1/models 9 auth resp viewer",
	"POST /api/v1/models 9 auth body resp analyst",
	"POST /api/v1/models/generate-query 9 auth body resp viewer",
	"POST /api/v1/models/import 9 auth body resp analyst",
	"POST /api/v1/models/parse-query 9 auth body resp viewer",
	"POST /api/v1/models/preview 9 auth body resp analyst",
	"POST /api/v1/models/test-extraction 9 auth body resp viewer",
	"DELETE /api/v1/models/{id} 9 auth resp analyst",
	"GET /api/v1/models/{id} 9 auth resp viewer",
	"PUT /api/v1/models/{id} 9 auth body resp analyst",
	"POST /api/v1/models/{id}/backfill 9 auth body resp analyst",
	"POST /api/v1/models/{id}/backfill/cancel 9 auth resp analyst",
	"GET /api/v1/models/{id}/data 9 auth resp viewer",
	"POST /api/v1/models/{id}/disable-alert 9 auth resp analyst",
	"POST /api/v1/models/{id}/enable-alert 9 auth resp analyst",
	"GET /api/v1/models/{id}/export 9 auth viewer",
	"GET /api/v1/models/{id}/histogram 9 auth resp viewer",
	"GET /api/v1/models/{id}/stats 9 auth resp viewer",
	"GET /api/v1/normalizers 9 auth resp viewer",
	"POST /api/v1/normalizers 9 auth body resp tenant_admin",
	"POST /api/v1/normalizers/import 9 auth body resp tenant_admin",
	"POST /api/v1/normalizers/preview 9 auth body resp tenant_admin",
	"GET /api/v1/normalizers/samples 9 auth resp tenant_admin",
	"DELETE /api/v1/normalizers/{id} 9 auth resp tenant_admin",
	"GET /api/v1/normalizers/{id} 9 auth resp tenant_admin",
	"PUT /api/v1/normalizers/{id} 9 auth body resp tenant_admin",
	"POST /api/v1/normalizers/{id}/duplicate 9 auth resp tenant_admin",
	"GET /api/v1/normalizers/{id}/export 9 auth tenant_admin",
	"POST /api/v1/normalizers/{id}/set-default 9 auth resp tenant_admin",
	"GET /api/v1/normalizers/{id}/tokens 9 auth resp tenant_admin",
	"GET /api/v1/notebooks 9 auth resp viewer",
	"POST /api/v1/notebooks 9 auth body resp analyst",
	"GET /api/v1/notebooks/active 9 auth resp viewer",
	"POST /api/v1/notebooks/active 9 auth resp analyst",
	"PUT /api/v1/notebooks/active 9 auth body resp viewer",
	"GET /api/v1/notebooks/ai-status 9 auth viewer",
	"POST /api/v1/notebooks/generate-from-comments 9 auth body resp analyst",
	"POST /api/v1/notebooks/import 9 auth body resp analyst",
	"DELETE /api/v1/notebooks/{id} 9 auth resp viewer",
	"GET /api/v1/notebooks/{id} 9 auth resp viewer",
	"PUT /api/v1/notebooks/{id} 9 auth body resp viewer",
	"GET /api/v1/notebooks/{id}/events 9 auth viewer",
	"POST /api/v1/notebooks/{id}/evidence 9 auth body resp analyst",
	"DELETE /api/v1/notebooks/{id}/evidence/{log_id} 9 auth resp analyst",
	"GET /api/v1/notebooks/{id}/export 9 auth viewer",
	"DELETE /api/v1/notebooks/{id}/lock 9 auth resp viewer",
	"POST /api/v1/notebooks/{id}/lock 9 auth resp viewer",
	"GET /api/v1/notebooks/{id}/presence 9 auth resp viewer",
	"POST /api/v1/notebooks/{id}/presence 9 auth resp viewer",
	"POST /api/v1/notebooks/{id}/sections 9 auth body resp viewer",
	"POST /api/v1/notebooks/{id}/sections/reorder 9 auth body resp viewer",
	"DELETE /api/v1/notebooks/{id}/sections/{section_id} 9 auth resp viewer",
	"PUT /api/v1/notebooks/{id}/sections/{section_id} 9 auth body resp viewer",
	"PUT /api/v1/notebooks/{id}/sections/{section_id}/results 9 auth body resp viewer",
	"POST /api/v1/notebooks/{id}/sections/{section_id}/summarize 9 auth resp viewer",
	"GET /api/v1/notebooks/{id}/summary 9 auth resp viewer",
	"GET /api/v1/notebooks/{id}/tags 9 auth viewer",
	"PUT /api/v1/notebooks/{id}/variables 9 auth body resp viewer",
	"GET /api/v1/notifications 9 auth resp viewer",
	"GET /api/v1/notifications/count 9 auth resp viewer",
	"POST /api/v1/notifications/read 9 auth authenticated",
	"GET /api/v1/openapi.json 9 auth authenticated",
	"GET /api/v1/prisms 9 auth resp viewer",
	"POST /api/v1/prisms 9 auth body resp tenant_admin",
	"DELETE /api/v1/prisms/{id} 9 auth resp tenant_admin",
	"GET /api/v1/prisms/{id} 9 auth resp tenant_admin",
	"PUT /api/v1/prisms/{id} 9 auth body resp tenant_admin",
	"GET /api/v1/prisms/{id}/api-keys 9 auth resp tenant_admin",
	"POST /api/v1/prisms/{id}/api-keys 9 auth body resp tenant_admin",
	"DELETE /api/v1/prisms/{id}/api-keys/{keyId} 9 auth tenant_admin",
	"GET /api/v1/prisms/{id}/api-keys/{keyId} 9 auth resp tenant_admin",
	"PUT /api/v1/prisms/{id}/api-keys/{keyId} 9 auth body resp tenant_admin",
	"POST /api/v1/prisms/{id}/api-keys/{keyId}/toggle 9 auth resp tenant_admin",
	"POST /api/v1/prisms/{id}/members 9 auth body resp tenant_admin",
	"DELETE /api/v1/prisms/{id}/members/{fractalID} 9 auth resp tenant_admin",
	"GET /api/v1/prisms/{id}/permissions 9 auth resp tenant_admin",
	"POST /api/v1/prisms/{id}/permissions 9 auth body resp tenant_admin",
	"DELETE /api/v1/prisms/{id}/permissions/{permId} 9 auth resp tenant_admin",
	"PUT /api/v1/prisms/{id}/permissions/{permId} 9 auth body resp tenant_admin",
	"POST /api/v1/prisms/{id}/select 9 auth resp viewer",
	"POST /api/v1/query 9 auth body resp viewer",
	"DELETE /api/v1/query-history 9 auth resp authenticated",
	"GET /api/v1/query-history 9 auth resp viewer",
	"POST /api/v1/query-history 9 auth body resp viewer",
	"DELETE /api/v1/query-history/{id} 9 auth resp viewer",
	"GET /api/v1/query/fields 9 auth resp viewer",
	"POST /api/v1/query/fieldstats 9 auth body resp viewer",
	"GET /api/v1/query/reference 9 auth viewer",
	"POST /api/v1/query/stream 9 auth body resp viewer",
	"POST /api/v1/query/validate 9 auth body resp viewer",
	"GET /api/v1/recall/available 9 auth viewer",
	"GET /api/v1/recall/{fractalID} 9 auth analyst",
	"POST /api/v1/recall/{fractalID} 9 auth body analyst",
	"GET /api/v1/recall/{fractalID}/estimate 9 auth analyst",
	"GET /api/v1/recall/{fractalID}/{id} 9 auth analyst",
	"POST /api/v1/recall/{fractalID}/{id}/cancel 9 auth analyst",
	"GET /api/v1/saved-queries 9 auth resp viewer",
	"POST /api/v1/saved-queries 9 auth body resp viewer",
	"DELETE /api/v1/saved-queries/{id} 9 auth resp viewer",
	"PUT /api/v1/saved-queries/{id} 9 auth body resp viewer",
	"DELETE /api/v1/saved-queries/{id}/favorite 9 auth resp viewer",
	"POST /api/v1/saved-queries/{id}/favorite 9 auth resp viewer",
	"POST /api/v1/saved-queries/{id}/use 9 auth resp viewer",
	"GET /api/v1/settings 9 auth resp tenant_admin",
	"POST /api/v1/settings 9 auth body resp tenant_admin",
	"GET /api/v1/shared/{token} 8 public public",
	"GET /api/v1/smtp-settings 9 auth resp tenant_admin",
	"POST /api/v1/smtp-settings 9 auth body tenant_admin",
	"GET /api/v1/status 9 auth resp tenant_admin",
	"GET /api/v1/system/archive 9 auth tenant_admin",
	"POST /api/v1/system/archive/clear 9 auth tenant_admin",
	"PUT /api/v1/system/archive/enabled 9 auth body tenant_admin",
	"POST /api/v1/system/archive/maintain/run 9 auth tenant_admin",
	"GET /api/v1/system/archive/restore 9 auth resp tenant_admin",
	"POST /api/v1/system/archive/restore 9 auth body tenant_admin",
	"POST /api/v1/system/archive/restore/{id}/cancel 9 auth tenant_admin",
	"POST /api/v1/system/archive/restore/{id}/resume 9 auth tenant_admin",
	"POST /api/v1/system/archive/spool/clear 9 auth tenant_admin",
	"POST /api/v1/system/distribution-queue/reset 9 auth body tenant_admin",
	"GET /api/v1/system/distribution-queue/shards 9 auth tenant_admin",
	"GET /api/v1/system/endpoint-analysis 9 auth tenant_admin",
	"POST /api/v1/system/endpoint-analysis 9 auth body tenant_admin",
	"GET /api/v1/system/pgr-calibration 9 auth tenant_admin",
	"GET /api/v1/system/pressure 9 auth viewer",
	"GET /api/v1/system/shared-links 9 auth viewer",
	"POST /api/v1/system/shared-links 9 auth body tenant_admin",
	"GET /api/v1/system/topology 9 auth viewer",
	"DELETE /api/v1/users 9 auth resp tenant_admin",
	"GET /api/v1/users 9 auth resp tenant_admin",
	"GET /api/v1/users/mtls-status 9 auth resp tenant_admin",
	"PUT /api/v1/users/{username} 9 auth body resp tenant_admin",
	"POST /api/v1/users/{username}/client-cert 9 auth body tenant_admin",
	"PUT /api/v1/users/{username}/enabled 9 auth body resp tenant_admin",
	"GET /api/v1/version 9 auth viewer",
	"GET /api/v1/webhooks 9 auth resp tenant_admin",
	"POST /api/v1/webhooks 9 auth body resp tenant_admin",
	"DELETE /api/v1/webhooks/{id} 9 auth tenant_admin",
	"GET /api/v1/webhooks/{id} 9 auth resp tenant_admin",
	"PUT /api/v1/webhooks/{id} 9 auth body resp tenant_admin",
	"POST /api/v1/webhooks/{id}/test 9 auth resp tenant_admin",
	"GET /go/search 7 public public",
	"POST /v1/logs 8 public body resp ingest_token",
}
