package main

// routeTable is every route the server mounts, in the form:
//
//	METHOD /path <middleware count> auth|public [body] [resp]
//
// "auth" means the route sits behind auth.AuthHandler.AuthMiddleware; "body"
// and "resp" mean the route declares a typed request and response.
//
// Regenerate after an intended change, then review every line of the diff:
//
//	go test ./cmd/bifract-server -run TestRouteTable -update
var routeTable = []string{
	"GET /* 7 public",
	"POST /_bulk 8 public resp",
	"PUT /_bulk 8 public resp",
	"GET /api/v1/admin/alert-stats 9 auth resp",
	"GET /api/v1/admin/ingest-daily 9 auth resp",
	"POST /api/v1/admin/kill-query 9 auth resp",
	"GET /api/v1/admin/metrics 9 auth resp",
	"GET /api/v1/admin/processes 9 auth resp",
	"GET /api/v1/admin/schema-fields 9 auth resp",
	"POST /api/v1/admin/schema-fields 9 auth body resp",
	"GET /api/v1/admin/schema-fields/export 9 auth",
	"DELETE /api/v1/admin/schema-fields/ignore/{name} 9 auth resp",
	"POST /api/v1/admin/schema-fields/ignore/{name} 9 auth resp",
	"POST /api/v1/admin/schema-fields/import 9 auth resp",
	"GET /api/v1/admin/schema-fields/insights 9 auth resp",
	"POST /api/v1/admin/schema-fields/refresh 9 auth resp",
	"POST /api/v1/admin/schema-fields/reset 9 auth body resp",
	"DELETE /api/v1/admin/schema-fields/{name} 9 auth resp",
	"GET /api/v1/alerts 10 auth resp",
	"POST /api/v1/alerts 10 auth body resp",
	"POST /api/v1/alerts/batch-toggle 10 auth body resp",
	"GET /api/v1/alerts/feed 9 auth resp",
	"POST /api/v1/alerts/feed/batch-toggle 9 auth body resp",
	"POST /api/v1/alerts/import 10 auth body resp",
	"DELETE /api/v1/alerts/{id} 10 auth",
	"GET /api/v1/alerts/{id} 10 auth resp",
	"PUT /api/v1/alerts/{id} 10 auth body resp",
	"POST /api/v1/alerts/{id}/duplicate 9 auth resp",
	"GET /api/v1/alerts/{id}/executions 10 auth resp",
	"POST /api/v1/alerts/{id}/toggle-feed 9 auth body",
	"GET /api/v1/attack/coverage 10 auth resp",
	"GET /api/v1/attack/gaps 10 auth resp",
	"GET /api/v1/attack/layer 10 auth",
	"GET /api/v1/attack/matrix 10 auth resp",
	"GET /api/v1/attack/techniques/{id}/gap 10 auth resp",
	"GET /api/v1/attack/techniques/{id}/rules 10 auth resp",
	"POST /api/v1/auth/admin-reset-password 9 auth body resp",
	"POST /api/v1/auth/change-password 9 auth body resp",
	"POST /api/v1/auth/invite/accept 7 public body resp",
	"POST /api/v1/auth/invite/reset 9 auth body resp",
	"GET /api/v1/auth/invite/validate 7 public resp",
	"POST /api/v1/auth/login 7 public body",
	"POST /api/v1/auth/logout 9 auth resp",
	"GET /api/v1/auth/oidc/callback 7 public",
	"GET /api/v1/auth/oidc/config 7 public",
	"GET /api/v1/auth/oidc/login 7 public",
	"PATCH /api/v1/auth/preferences 9 auth body resp",
	"POST /api/v1/auth/register 9 auth body resp",
	"GET /api/v1/auth/user 9 auth resp",
	"DELETE /api/v1/chat/conversations 10 auth resp",
	"GET /api/v1/chat/conversations 10 auth resp",
	"POST /api/v1/chat/conversations 10 auth body resp",
	"DELETE /api/v1/chat/conversations/{id} 10 auth resp",
	"PATCH /api/v1/chat/conversations/{id} 10 auth body resp",
	"GET /api/v1/chat/conversations/{id}/libraries 10 auth resp",
	"PATCH /api/v1/chat/conversations/{id}/libraries 10 auth body resp",
	"DELETE /api/v1/chat/conversations/{id}/messages 10 auth resp",
	"GET /api/v1/chat/conversations/{id}/messages 10 auth resp",
	"POST /api/v1/chat/conversations/{id}/stream 10 auth body",
	"GET /api/v1/chat/instructions 9 auth resp",
	"POST /api/v1/chat/instructions 9 auth body resp",
	"DELETE /api/v1/chat/instructions/{instructionId} 9 auth resp",
	"PUT /api/v1/chat/instructions/{instructionId} 9 auth body resp",
	"POST /api/v1/comments 9 auth body resp",
	"POST /api/v1/comments/bulk-add-tag 9 auth body",
	"POST /api/v1/comments/bulk-delete 9 auth body",
	"POST /api/v1/comments/bulk-remove-tag 9 auth body",
	"GET /api/v1/comments/flat 9 auth resp",
	"POST /api/v1/comments/graph/log-fields 9 auth body resp",
	"GET /api/v1/comments/tags 9 auth resp",
	"DELETE /api/v1/comments/{id} 9 auth resp",
	"GET /api/v1/comments/{id} 9 auth resp",
	"PUT /api/v1/comments/{id} 9 auth body resp",
	"GET /api/v1/context-links 9 auth resp",
	"POST /api/v1/context-links 9 auth body resp",
	"GET /api/v1/context-links/enabled 9 auth resp",
	"DELETE /api/v1/context-links/{id} 9 auth resp",
	"GET /api/v1/context-links/{id} 9 auth resp",
	"PUT /api/v1/context-links/{id} 9 auth body resp",
	"GET /api/v1/dashboards 10 auth resp",
	"POST /api/v1/dashboards 10 auth body resp",
	"POST /api/v1/dashboards/import 10 auth resp",
	"DELETE /api/v1/dashboards/{id} 10 auth resp",
	"GET /api/v1/dashboards/{id} 10 auth resp",
	"PUT /api/v1/dashboards/{id} 10 auth body resp",
	"GET /api/v1/dashboards/{id}/events 10 auth",
	"POST /api/v1/dashboards/{id}/execute 10 auth resp",
	"GET /api/v1/dashboards/{id}/export 10 auth",
	"GET /api/v1/dashboards/{id}/presence 10 auth resp",
	"POST /api/v1/dashboards/{id}/presence 10 auth resp",
	"PUT /api/v1/dashboards/{id}/refresh-interval 10 auth body resp",
	"GET /api/v1/dashboards/{id}/shared-links 10 auth resp",
	"POST /api/v1/dashboards/{id}/shared-links 10 auth body",
	"DELETE /api/v1/dashboards/{id}/shared-links/{link_id} 10 auth resp",
	"PUT /api/v1/dashboards/{id}/variables 10 auth body resp",
	"POST /api/v1/dashboards/{id}/widgets 10 auth body resp",
	"DELETE /api/v1/dashboards/{id}/widgets/{widget_id} 10 auth resp",
	"PUT /api/v1/dashboards/{id}/widgets/{widget_id} 10 auth body resp",
	"POST /api/v1/dashboards/{id}/widgets/{widget_id}/execute 10 auth body",
	"PUT /api/v1/dashboards/{id}/widgets/{widget_id}/layout 10 auth body resp",
	"GET /api/v1/dictionaries 9 auth resp",
	"POST /api/v1/dictionaries 9 auth body resp",
	"DELETE /api/v1/dictionaries/{id} 9 auth resp",
	"GET /api/v1/dictionaries/{id} 9 auth resp",
	"PUT /api/v1/dictionaries/{id} 9 auth body resp",
	"POST /api/v1/dictionaries/{id}/columns 9 auth body resp",
	"DELETE /api/v1/dictionaries/{id}/columns/{name} 9 auth resp",
	"DELETE /api/v1/dictionaries/{id}/columns/{name}/key 9 auth resp",
	"POST /api/v1/dictionaries/{id}/columns/{name}/key 9 auth resp",
	"GET /api/v1/dictionaries/{id}/data 9 auth resp",
	"POST /api/v1/dictionaries/{id}/data 9 auth body resp",
	"DELETE /api/v1/dictionaries/{id}/data/{key} 9 auth resp",
	"GET /api/v1/dictionaries/{id}/export 9 auth",
	"POST /api/v1/dictionaries/{id}/import 9 auth resp",
	"POST /api/v1/dictionaries/{id}/reload 9 auth resp",
	"GET /api/v1/dictionary-actions 9 auth resp",
	"POST /api/v1/dictionary-actions 9 auth body resp",
	"DELETE /api/v1/dictionary-actions/{id} 9 auth resp",
	"GET /api/v1/dictionary-actions/{id} 9 auth resp",
	"PUT /api/v1/dictionary-actions/{id} 9 auth body resp",
	"GET /api/v1/email-actions 9 auth resp",
	"POST /api/v1/email-actions 9 auth body resp",
	"DELETE /api/v1/email-actions/{id} 9 auth",
	"GET /api/v1/email-actions/{id} 9 auth resp",
	"PUT /api/v1/email-actions/{id} 9 auth body resp",
	"POST /api/v1/email-actions/{id}/test 9 auth resp",
	"GET /api/v1/feeds 9 auth resp",
	"POST /api/v1/feeds 9 auth body resp",
	"DELETE /api/v1/feeds/{id} 9 auth",
	"GET /api/v1/feeds/{id} 9 auth resp",
	"PUT /api/v1/feeds/{id} 9 auth body resp",
	"GET /api/v1/feeds/{id}/alerts 9 auth resp",
	"POST /api/v1/feeds/{id}/alerts/disable-all 9 auth",
	"POST /api/v1/feeds/{id}/alerts/enable-all 9 auth",
	"POST /api/v1/feeds/{id}/sync 9 auth",
	"GET /api/v1/fractal-actions 9 auth resp",
	"POST /api/v1/fractal-actions 9 auth body resp",
	"DELETE /api/v1/fractal-actions/{id} 9 auth",
	"GET /api/v1/fractal-actions/{id} 9 auth resp",
	"PUT /api/v1/fractal-actions/{id} 9 auth body resp",
	"GET /api/v1/fractals 9 auth resp",
	"POST /api/v1/fractals 9 auth body resp",
	"POST /api/v1/fractals/stats/refresh 9 auth",
	"DELETE /api/v1/fractals/{id} 9 auth",
	"GET /api/v1/fractals/{id} 9 auth resp",
	"PUT /api/v1/fractals/{id} 9 auth body resp",
	"GET /api/v1/fractals/{id}/api-keys 9 auth resp",
	"POST /api/v1/fractals/{id}/api-keys 9 auth body resp",
	"DELETE /api/v1/fractals/{id}/api-keys/{keyId} 9 auth",
	"GET /api/v1/fractals/{id}/api-keys/{keyId} 9 auth resp",
	"PUT /api/v1/fractals/{id}/api-keys/{keyId} 9 auth body resp",
	"POST /api/v1/fractals/{id}/api-keys/{keyId}/toggle 9 auth resp",
	"PUT /api/v1/fractals/{id}/archive-retention 9 auth body",
	"PUT /api/v1/fractals/{id}/disk-quota 9 auth body",
	"GET /api/v1/fractals/{id}/ingest-tokens 9 auth resp",
	"POST /api/v1/fractals/{id}/ingest-tokens 9 auth body resp",
	"DELETE /api/v1/fractals/{id}/ingest-tokens/{tokenId} 9 auth",
	"GET /api/v1/fractals/{id}/ingest-tokens/{tokenId} 9 auth resp",
	"PUT /api/v1/fractals/{id}/ingest-tokens/{tokenId} 9 auth body resp",
	"POST /api/v1/fractals/{id}/ingest-tokens/{tokenId}/toggle 9 auth resp",
	"GET /api/v1/fractals/{id}/permissions 9 auth resp",
	"POST /api/v1/fractals/{id}/permissions 9 auth body resp",
	"DELETE /api/v1/fractals/{id}/permissions/{permId} 9 auth",
	"PUT /api/v1/fractals/{id}/permissions/{permId} 9 auth body",
	"PUT /api/v1/fractals/{id}/retention 9 auth body",
	"POST /api/v1/fractals/{id}/select 9 auth resp",
	"GET /api/v1/fractals/{id}/stats 9 auth resp",
	"GET /api/v1/groups 9 auth",
	"POST /api/v1/groups 9 auth body",
	"DELETE /api/v1/groups/{id} 9 auth",
	"GET /api/v1/groups/{id} 9 auth",
	"PUT /api/v1/groups/{id} 9 auth body",
	"GET /api/v1/groups/{id}/members 9 auth",
	"POST /api/v1/groups/{id}/members 9 auth body",
	"DELETE /api/v1/groups/{id}/members/{username} 9 auth",
	"GET /api/v1/health 7 public",
	"GET /api/v1/health/clickhouse 9 auth",
	"POST /api/v1/ingest 8 public resp",
	"GET /api/v1/instruction-libraries 9 auth resp",
	"POST /api/v1/instruction-libraries 9 auth body resp",
	"GET /api/v1/instruction-libraries/ensure-default 9 auth resp",
	"DELETE /api/v1/instruction-libraries/{id} 9 auth",
	"GET /api/v1/instruction-libraries/{id} 9 auth resp",
	"PUT /api/v1/instruction-libraries/{id} 9 auth body resp",
	"GET /api/v1/instruction-libraries/{id}/folders 9 auth resp",
	"POST /api/v1/instruction-libraries/{id}/folders 9 auth body resp",
	"DELETE /api/v1/instruction-libraries/{id}/folders/{folderId} 9 auth",
	"PUT /api/v1/instruction-libraries/{id}/folders/{folderId} 9 auth body resp",
	"GET /api/v1/instruction-libraries/{id}/pages 9 auth resp",
	"POST /api/v1/instruction-libraries/{id}/pages 9 auth body resp",
	"DELETE /api/v1/instruction-libraries/{id}/pages/{pageId} 9 auth",
	"GET /api/v1/instruction-libraries/{id}/pages/{pageId} 9 auth resp",
	"PUT /api/v1/instruction-libraries/{id}/pages/{pageId} 9 auth body resp",
	"GET /api/v1/instruction-libraries/{id}/pages/{pageId}/backlinks 9 auth resp",
	"PATCH /api/v1/instruction-libraries/{id}/pages/{pageId}/move 9 auth body",
	"POST /api/v1/instruction-libraries/{id}/sync 9 auth resp",
	"POST /api/v1/internal/ingest/{fractal} 9 public resp",
	"DELETE /api/v1/logs 9 auth resp",
	"POST /api/v1/logs/by-timestamp 9 auth body resp",
	"GET /api/v1/logs/commented 9 auth resp",
	"GET /api/v1/logs/fields 9 auth resp",
	"GET /api/v1/logs/histogram 9 auth",
	"GET /api/v1/logs/recent 9 auth",
	"DELETE /api/v1/logs/{log_id}/comments 9 auth resp",
	"GET /api/v1/logs/{log_id}/comments 9 auth resp",
	"GET /api/v1/models 9 auth resp",
	"POST /api/v1/models 9 auth body resp",
	"POST /api/v1/models/generate-query 9 auth body resp",
	"POST /api/v1/models/import 9 auth resp",
	"POST /api/v1/models/parse-query 9 auth body resp",
	"POST /api/v1/models/preview 9 auth body resp",
	"POST /api/v1/models/test-extraction 9 auth body resp",
	"DELETE /api/v1/models/{id} 9 auth resp",
	"GET /api/v1/models/{id} 9 auth resp",
	"PUT /api/v1/models/{id} 9 auth body resp",
	"POST /api/v1/models/{id}/backfill 9 auth body resp",
	"POST /api/v1/models/{id}/backfill/cancel 9 auth resp",
	"GET /api/v1/models/{id}/data 9 auth resp",
	"POST /api/v1/models/{id}/disable-alert 9 auth resp",
	"POST /api/v1/models/{id}/enable-alert 9 auth resp",
	"GET /api/v1/models/{id}/export 9 auth",
	"GET /api/v1/models/{id}/histogram 9 auth resp",
	"GET /api/v1/models/{id}/stats 9 auth resp",
	"GET /api/v1/normalizers 9 auth resp",
	"POST /api/v1/normalizers 9 auth body resp",
	"POST /api/v1/normalizers/import 9 auth resp",
	"POST /api/v1/normalizers/preview 9 auth body resp",
	"GET /api/v1/normalizers/samples 9 auth resp",
	"DELETE /api/v1/normalizers/{id} 9 auth resp",
	"GET /api/v1/normalizers/{id} 9 auth resp",
	"PUT /api/v1/normalizers/{id} 9 auth body resp",
	"POST /api/v1/normalizers/{id}/duplicate 9 auth resp",
	"GET /api/v1/normalizers/{id}/export 9 auth",
	"POST /api/v1/normalizers/{id}/set-default 9 auth resp",
	"GET /api/v1/normalizers/{id}/tokens 9 auth resp",
	"GET /api/v1/notebooks 10 auth resp",
	"POST /api/v1/notebooks 10 auth body resp",
	"GET /api/v1/notebooks/ai-status 10 auth",
	"POST /api/v1/notebooks/generate-from-comments 10 auth body resp",
	"POST /api/v1/notebooks/import 10 auth resp",
	"DELETE /api/v1/notebooks/{id} 10 auth resp",
	"GET /api/v1/notebooks/{id} 10 auth resp",
	"PUT /api/v1/notebooks/{id} 10 auth body resp",
	"GET /api/v1/notebooks/{id}/events 10 auth",
	"GET /api/v1/notebooks/{id}/export 10 auth",
	"GET /api/v1/notebooks/{id}/presence 10 auth resp",
	"POST /api/v1/notebooks/{id}/presence 10 auth resp",
	"POST /api/v1/notebooks/{id}/sections 10 auth body resp",
	"POST /api/v1/notebooks/{id}/sections/reorder 10 auth body resp",
	"DELETE /api/v1/notebooks/{id}/sections/{section_id} 10 auth resp",
	"PUT /api/v1/notebooks/{id}/sections/{section_id} 10 auth body resp",
	"POST /api/v1/notebooks/{id}/sections/{section_id}/execute 10 auth body resp",
	"PUT /api/v1/notebooks/{id}/sections/{section_id}/results 10 auth body resp",
	"POST /api/v1/notebooks/{id}/sections/{section_id}/summarize 10 auth resp",
	"GET /api/v1/notebooks/{id}/tags 10 auth",
	"PUT /api/v1/notebooks/{id}/variables 10 auth body resp",
	"GET /api/v1/notifications 9 auth resp",
	"GET /api/v1/notifications/count 9 auth resp",
	"POST /api/v1/notifications/read 9 auth",
	"GET /api/v1/prisms 9 auth resp",
	"POST /api/v1/prisms 9 auth body resp",
	"DELETE /api/v1/prisms/{id} 9 auth resp",
	"GET /api/v1/prisms/{id} 9 auth resp",
	"PUT /api/v1/prisms/{id} 9 auth body resp",
	"GET /api/v1/prisms/{id}/api-keys 9 auth resp",
	"POST /api/v1/prisms/{id}/api-keys 9 auth body resp",
	"DELETE /api/v1/prisms/{id}/api-keys/{keyId} 9 auth",
	"GET /api/v1/prisms/{id}/api-keys/{keyId} 9 auth resp",
	"PUT /api/v1/prisms/{id}/api-keys/{keyId} 9 auth body resp",
	"POST /api/v1/prisms/{id}/api-keys/{keyId}/toggle 9 auth resp",
	"POST /api/v1/prisms/{id}/members 9 auth body resp",
	"DELETE /api/v1/prisms/{id}/members/{fractalID} 9 auth resp",
	"GET /api/v1/prisms/{id}/permissions 9 auth resp",
	"POST /api/v1/prisms/{id}/permissions 9 auth body resp",
	"DELETE /api/v1/prisms/{id}/permissions/{permId} 9 auth resp",
	"PUT /api/v1/prisms/{id}/permissions/{permId} 9 auth body resp",
	"POST /api/v1/prisms/{id}/select 9 auth resp",
	"POST /api/v1/query 9 auth resp",
	"DELETE /api/v1/query-history 9 auth resp",
	"GET /api/v1/query-history 9 auth resp",
	"POST /api/v1/query-history 9 auth body resp",
	"DELETE /api/v1/query-history/{id} 9 auth resp",
	"GET /api/v1/query/fields 9 auth resp",
	"POST /api/v1/query/fieldstats 9 auth",
	"GET /api/v1/query/reference 9 auth",
	"POST /api/v1/query/stream 9 auth resp",
	"POST /api/v1/query/validate 9 auth body resp",
	"GET /api/v1/recall/available 9 auth",
	"GET /api/v1/recall/{fractalID} 9 auth",
	"POST /api/v1/recall/{fractalID} 9 auth body",
	"GET /api/v1/recall/{fractalID}/estimate 9 auth",
	"GET /api/v1/recall/{fractalID}/{id} 9 auth",
	"POST /api/v1/recall/{fractalID}/{id}/cancel 9 auth",
	"GET /api/v1/saved-queries 9 auth resp",
	"POST /api/v1/saved-queries 9 auth body resp",
	"DELETE /api/v1/saved-queries/{id} 9 auth resp",
	"PUT /api/v1/saved-queries/{id} 9 auth body resp",
	"DELETE /api/v1/saved-queries/{id}/favorite 9 auth resp",
	"POST /api/v1/saved-queries/{id}/favorite 9 auth resp",
	"POST /api/v1/saved-queries/{id}/use 9 auth resp",
	"GET /api/v1/settings 9 auth resp",
	"POST /api/v1/settings 9 auth body resp",
	"GET /api/v1/shared/{token} 8 public",
	"GET /api/v1/smtp-settings 9 auth resp",
	"POST /api/v1/smtp-settings 9 auth body",
	"GET /api/v1/status 9 auth resp",
	"GET /api/v1/system/archive 9 auth",
	"POST /api/v1/system/archive/clear 9 auth",
	"PUT /api/v1/system/archive/enabled 9 auth body",
	"POST /api/v1/system/archive/maintain/run 9 auth",
	"GET /api/v1/system/archive/restore 9 auth resp",
	"POST /api/v1/system/archive/restore 9 auth body",
	"POST /api/v1/system/archive/restore/{id}/cancel 9 auth",
	"POST /api/v1/system/archive/restore/{id}/resume 9 auth",
	"POST /api/v1/system/archive/spool/clear 9 auth",
	"POST /api/v1/system/distribution-queue/reset 9 auth body",
	"GET /api/v1/system/distribution-queue/shards 9 auth",
	"GET /api/v1/system/endpoint-analysis 9 auth",
	"POST /api/v1/system/endpoint-analysis 9 auth body",
	"GET /api/v1/system/pressure 9 auth",
	"GET /api/v1/system/shared-links 9 auth",
	"POST /api/v1/system/shared-links 9 auth body",
	"GET /api/v1/system/topology 9 auth",
	"DELETE /api/v1/users 9 auth resp",
	"GET /api/v1/users 9 auth resp",
	"GET /api/v1/users/mtls-status 9 auth resp",
	"PUT /api/v1/users/{username} 9 auth body resp",
	"POST /api/v1/users/{username}/client-cert 9 auth body",
	"PUT /api/v1/users/{username}/enabled 9 auth body resp",
	"GET /api/v1/version 9 auth",
	"GET /api/v1/webhooks 9 auth resp",
	"POST /api/v1/webhooks 9 auth body resp",
	"DELETE /api/v1/webhooks/{id} 9 auth",
	"GET /api/v1/webhooks/{id} 9 auth resp",
	"PUT /api/v1/webhooks/{id} 9 auth body resp",
	"POST /api/v1/webhooks/{id}/test 9 auth resp",
	"GET /go/search 7 public",
	"POST /v1/logs 8 public resp",
}
