// Package attack overlays Bifract's detection rules on the MITRE ATT&CK matrix.
//
// The Enterprise matrix is embedded (gzipped, generated by cmd/bifract-attackgen)
// rather than fetched at runtime: Bifract must work in air-gapped installs, and a
// startup dependency on GitHub is not acceptable for a security tool.
package attack

import (
	"compress/gzip"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
	"sync"
)

//go:embed data/enterprise-attack.json.gz
var dataFS embed.FS

// Tactic is one column of the matrix, in kill-chain order.
type Tactic struct {
	ID    string `json:"id"`    // TA0003
	Short string `json:"short"` // persistence (the slug Sigma tags use)
	Name  string `json:"name"`  // Persistence
}

// Technique is one cell. Platforms and LogSources are indexes into the matrix
// string tables, which keeps the embedded file small.
type Technique struct {
	ID         string   `json:"id"` // T1543 or T1543.003
	Name       string   `json:"name"`
	Tactics    []string `json:"tactics"` // tactic shortnames
	Sub        bool     `json:"sub,omitempty"`
	Parent     string   `json:"parent,omitempty"`
	Deprecated bool     `json:"deprecated,omitempty"`
	Platforms  []int    `json:"platforms,omitempty"`
	LogSources []int    `json:"log_sources,omitempty"`
}

// Matrix is the embedded ATT&CK dataset. It is immutable after load.
type Matrix struct {
	Version    string            `json:"version"`
	Domain     string            `json:"domain"`
	Tactics    []Tactic          `json:"tactics"`
	Techniques []Technique       `json:"techniques"`
	Platforms  []string          `json:"platforms"`
	LogSources []string          `json:"log_sources"`
	RevokedBy  map[string]string `json:"revoked_by"`

	byID       map[string]*Technique
	byTactic   map[string][]*Technique
	subsOf     map[string][]*Technique
	tacticByID map[string]*Tactic
}

var (
	loadOnce sync.Once
	loaded   *Matrix
	loadErr  error
)

// Get returns the embedded matrix, decompressing and indexing it on first call.
func Get() (*Matrix, error) {
	loadOnce.Do(func() {
		loaded, loadErr = load()
	})
	return loaded, loadErr
}

// MustGet is for callers that cannot proceed without the matrix. A failure here
// means the embedded data file is corrupt, which is a build-time defect.
func MustGet() *Matrix {
	m, err := Get()
	if err != nil {
		panic("attack: " + err.Error())
	}
	return m
}

func load() (*Matrix, error) {
	f, err := dataFS.Open("data/enterprise-attack.json.gz")
	if err != nil {
		return nil, fmt.Errorf("open embedded matrix: %w", err)
	}
	defer f.Close()

	zr, err := gzip.NewReader(f)
	if err != nil {
		return nil, fmt.Errorf("gunzip embedded matrix: %w", err)
	}
	defer zr.Close()

	raw, err := io.ReadAll(zr)
	if err != nil {
		return nil, fmt.Errorf("read embedded matrix: %w", err)
	}

	var m Matrix
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("decode embedded matrix: %w", err)
	}
	if len(m.Tactics) == 0 || len(m.Techniques) == 0 {
		return nil, fmt.Errorf("embedded matrix is empty")
	}

	m.index()
	return &m, nil
}

func (m *Matrix) index() {
	m.byID = make(map[string]*Technique, len(m.Techniques))
	m.byTactic = make(map[string][]*Technique, len(m.Tactics))
	m.subsOf = make(map[string][]*Technique)
	m.tacticByID = make(map[string]*Tactic, len(m.Tactics)*2)

	for i := range m.Tactics {
		t := &m.Tactics[i]
		m.tacticByID[t.Short] = t
		m.tacticByID[strings.ToLower(t.ID)] = t
	}
	for i := range m.Techniques {
		t := &m.Techniques[i]
		m.byID[t.ID] = t
		if t.Sub {
			m.subsOf[t.Parent] = append(m.subsOf[t.Parent], t)
			continue
		}
		for _, short := range t.Tactics {
			m.byTactic[short] = append(m.byTactic[short], t)
		}
	}
	for _, subs := range m.subsOf {
		sort.Slice(subs, func(i, j int) bool { return subs[i].ID < subs[j].ID })
	}
	for _, techs := range m.byTactic {
		sort.Slice(techs, func(i, j int) bool { return techs[i].Name < techs[j].Name })
	}
}

// Technique returns the technique with the given ID, or nil.
func (m *Matrix) Technique(id string) *Technique { return m.byID[id] }

// TechniquesForTactic returns the top-level techniques in a tactic column,
// ordered by name. Sub-techniques are reached via SubTechniques.
func (m *Matrix) TechniquesForTactic(short string) []*Technique { return m.byTactic[short] }

// SubTechniques returns the sub-techniques of a technique, ordered by ID.
func (m *Matrix) SubTechniques(id string) []*Technique { return m.subsOf[id] }

// Tactic resolves a tactic by shortname or by ID (case-insensitive).
func (m *Matrix) Tactic(key string) *Tactic { return m.tacticByID[strings.ToLower(key)] }

// PlatformNames resolves a technique's platform indexes.
func (m *Matrix) PlatformNames(t *Technique) []string { return resolve(m.Platforms, t.Platforms) }

// LogSourceNames resolves a technique's log source indexes. These are the
// telemetry MITRE expects the technique to be detectable in, which is what makes
// an uncovered technique actionable rather than just red.
func (m *Matrix) LogSourceNames(t *Technique) []string { return resolve(m.LogSources, t.LogSources) }

func resolve(table []string, idx []int) []string {
	if len(idx) == 0 {
		return nil
	}
	out := make([]string, 0, len(idx))
	for _, i := range idx {
		if i >= 0 && i < len(table) {
			out = append(out, table[i])
		}
	}
	return out
}
