ALTER TABLE fractals ADD COLUMN IF NOT EXISTS archive_schedule VARCHAR(20) DEFAULT 'never';
ALTER TABLE fractals ADD COLUMN IF NOT EXISTS max_archives INTEGER DEFAULT NULL;
ALTER TABLE archives ADD COLUMN IF NOT EXISTS archive_type VARCHAR(20) NOT NULL DEFAULT 'adhoc';
