ALTER TABLE archives ADD COLUMN IF NOT EXISTS format_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE archives ADD COLUMN IF NOT EXISTS archive_end_ts TIMESTAMP;
ALTER TABLE archives ADD COLUMN IF NOT EXISTS cursor_ts TIMESTAMP;
ALTER TABLE archives ADD COLUMN IF NOT EXISTS cursor_id TEXT;
